lsi: false
safe: true
incremental: false
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
exclude:
  - secret.py
  - zoom.py
  - make_program.py
  - send_emails.py
  - zoom_data
  - vendor
  - Gemfile
